"""updated address to location and updated table name of department

Revision ID: 35d1b720ebd9
Revises: 4660adb80b9e
Create Date: 2024-08-23 11:55:35.562171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d1b720ebd9'
down_revision = '4660adb80b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    op.alter_column(table_name='departments', column_name = 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    op.alter_column(table_name='department', column_name = 'location', new_column_name='address')
    # ### end Alembic commands ###
